apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-testns1
  namespace: argocd 
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: namespacetest
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/my-apps/app-1
    repoURL: https://github.com/Rajendra08/argocd-apps-of-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
